<p class="red-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
<p class="pink-text">Impedit architecto, totam hic sunt eum odio, deleniti.</p>
<p class="purple-text">Similique ex, expedita minus assumenda a magni beatae dolorum itaque.</p>
<p class="deep-purple-text">Veritatis eum libero nam, adipisci, necessitatibus eos.</p>
<p class="indigo-text">Sapiente, ea. Molestias sunt nihil saepe numquam quas perferendis.</p>
<p class="blue-text">Sapiente sit, possimus maiores, quo alias corporis cum eum nesciunt.</p>
<p class="light-blue-text">Corrupti adipisci, praesentium iusto eos, iure debitis modi.</p>
<p class="cyan-text">Odio autem veritatis aliquam consequuntur ea voluptatibus.</p>
<p class="teal-text">Similique, adipisci ea, sequi magnam sit inventore.</p>
<p class="green-text">Eos et vitae, odit deserunt dignissimos voluptas.</p>
<p class="light-green-text">Fugit nihil numquam inventore accusantium tenetur ex est.</p>
<p class="lime-text">Sed odit inventore illum excepturi officia, reiciendis numquam modi.</p>
<p class="yellow-text">At odio animi distinctio, aut enim tempora nobis error odit mollitia.</p>
<p class="amber-text">Quo at accusamus vel earum hic, inventore non, minima sint.</p>
<p class="orange-text">Iusto odit eos distinctio temporibus voluptates ad, illo repellat.</p>
<p class="deep-orange-text">Quas fugit fuga assumenda nihil esse et culpa reiciendis voluptatum.</p>
<p class="brown-text">Excepturi iusto amet sunt illo ad debitis quibusdam eius, consequatur.</p>
<p class="grey-text">Non sint nulla incidunt, odit repellat tempore, veniam ratione fugit.</p>
<p class="blue-grey-text">Eius, provident. Quo similique, repellat atque voluptas explicabo odio.</p>
<p class="red-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
<p class="pink-text">Impedit architecto, totam hic sunt eum odio, deleniti.</p>
<p class="purple-text">Similique ex, expedita minus assumenda a magni beatae dolorum itaque.</p>
<p class="deep-purple-text">Veritatis eum libero nam, adipisci, necessitatibus eos.</p>
<p class="indigo-text">Sapiente, ea. Molestias sunt nihil saepe numquam quas perferendis.</p>
<p class="blue-text">Sapiente sit, possimus maiores, quo alias corporis cum eum nesciunt.</p>
<p class="light-blue-text">Corrupti adipisci, praesentium iusto eos, iure debitis modi.</p>
<p class="cyan-text">Odio autem veritatis aliquam consequuntur ea voluptatibus.</p>
<p class="teal-text">Similique, adipisci ea, sequi magnam sit inventore.</p>
<p class="green-text">Eos et vitae, odit deserunt dignissimos voluptas.</p>
<p class="text-black-50">.text-black-50</p>